name: extract_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.5  # For picking images from gallery or camera
  tflite_flutter: ^0.11.0  # For TensorFlow Lite model inference
  image: ^4.1.3
  path_provider: ^2.1.1  # For file paths
  path: ^1.8.3  # For path manipulation
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/guides/open_phone.png
    - assets/guides/dark_phone.png
    - assets/guides/light_phone.png
    - assets/guides/blur_phone.png
    - assets/guides/unblur_phone.png
    - assets/guides/mul_phone1.png
    - assets/guides/mul_phone2.png
    - assets/guides/mul_phone3.png
    - assets/guides/open_laptop.png
    - assets/guides/dark_laptop.png
    - assets/guides/light_laptop.png
    - assets/guides/blur_laptop.png
    - assets/guides/unblur_laptop.png
    - assets/guides/mul_laptop1.png
    - assets/guides/mul_laptop2.png
    - assets/guides/mul_laptop3.png
    - assets/guides/open_desktop.png
    - assets/guides/dark_desktop.png
    - assets/guides/light_desktop.png
    - assets/guides/blur_desktop.png
    - assets/guides/unblur_desktop.png
    - assets/guides/mul_desktop1.png
    - assets/guides/mul_desktop2.png
    - assets/guides/mul_desktop3.png
    - assets/guides/open_router.png
    - assets/guides/light_router.png
    - assets/guides/dark_router.png
    - assets/guides/blur_router.png
    - assets/guides/unblur_router.png
    - assets/guides/open_landline.png
    - assets/guides/light_landline.png
    - assets/guides/dark_landline.png
    - assets/guides/blur_landline.png
    - assets/guides/unblur_landline.png
    - assets/guides/add_img.png
    - assets/guides/default.png
    - assets/desktop_instructions.json
    - assets/laptop_instructions.json
    - assets/landline_instructions.json
    - assets/router_instructions.json

    - assets/models/laptop/best_laptop_float16.tflite
    - assets/models/computer/best_computer_float16.tflite
    - assets/models/smartphone/best_phone_float16.tflite
    - assets/models/telecom/best_router-1_float16.tflite

    - assets/models/laptop/labels.txt
    - assets/models/computer/labels.txt
    - assets/models/smartphone/labels.txt
    - assets/models/telecom/labels.txt


  