name: extract_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0  # Required for initializing Firebase
  cloud_firestore: ^5.6.7 # For Firestore database
  firebase_storage: ^12.4.5 # For Firebase Storage
  firebase_auth: ^5.5.3 # For Firebase Authentication
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.5  # For picking images from gallery or camera
  tflite_flutter: ^0.11.0  # For TensorFlow Lite model inference
  image: ^4.1.3
  path_provider: ^2.1.1  # For file paths
  path: ^1.8.3  # For path manipulation
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.2.4
  timeago: ^3.2.0 # For displaying time in a human-readable format
  lottie: ^2.3.2 # For Lottie animations
  animated_splash_screen: ^1.3.0 # For splash screen animations
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.11
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  image_path: "assets/guides/app_icon_2.png"

flutter:
  uses-material-design: true
  assets:

    - assets/splash.json
    # Guide images + app icon
    - assets/guides/

    # Assistance images
    - assets/img_assistance/

    # Knowledge-base
    - assets/desktop_instructions.json
    - assets/laptop_instructions.json
    - assets/landline_instructions.json
    - assets/router_instructions.json

    # TFLite models 
    - assets/models/laptop/best_laptop_float16.tflite
    - assets/models/computer/computer-final.tflite
    - assets/models/smartphone/best_phone_float16.tflite
    - assets/models/telecom/best_router-1_float16.tflite

    # Model labels
    - assets/models/laptop/labels.txt
    - assets/models/computer/labels.txt
    - assets/models/smartphone/labels.txt
    - assets/models/telecom/labels.txt
    - assets/smartphone_instructions.json


