// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQddy21yDEvdvamf-LWTaYSVhmxz4Wm00',
    appId: '1:912116391395:web:6d42f8baa5740dac4c14d6',
    messagingSenderId: '912116391395',
    projectId: 'e-xtract-mobile-app',
    authDomain: 'e-xtract-mobile-app.firebaseapp.com',
    storageBucket: 'e-xtract-mobile-app.firebasestorage.app',
    measurementId: 'G-T1E0L27LT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfyvMQ_Xt9jltaN5SDBi_RWhgDOgtyww',
    appId: '1:912116391395:android:757b6db734081ae74c14d6',
    messagingSenderId: '912116391395',
    projectId: 'e-xtract-mobile-app',
    storageBucket: 'e-xtract-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGIGd2lLo2hrGHNQ-iwF7Mxsb_ru_UoeE',
    appId: '1:912116391395:ios:944344fa67e660844c14d6',
    messagingSenderId: '912116391395',
    projectId: 'e-xtract-mobile-app',
    storageBucket: 'e-xtract-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.extractApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGIGd2lLo2hrGHNQ-iwF7Mxsb_ru_UoeE',
    appId: '1:912116391395:ios:944344fa67e660844c14d6',
    messagingSenderId: '912116391395',
    projectId: 'e-xtract-mobile-app',
    storageBucket: 'e-xtract-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.extractApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQddy21yDEvdvamf-LWTaYSVhmxz4Wm00',
    appId: '1:912116391395:web:fc0010cdf0a6fc114c14d6',
    messagingSenderId: '912116391395',
    projectId: 'e-xtract-mobile-app',
    authDomain: 'e-xtract-mobile-app.firebaseapp.com',
    storageBucket: 'e-xtract-mobile-app.firebasestorage.app',
    measurementId: 'G-SPR297Q5SP',
  );
}
